include: package:lints/recommended.yaml

analyzer:
  exclude: [ build/** ]
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - cancel_subscriptions
    - prefer_const_constructors
    - sized_box_for_whitespace
    - camel_case_types
    - sort_pub_dependencies
    - always_use_package_imports
    - avoid_relative_lib_imports
    - avoid_print
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - avoid_type_to_string
    - avoid_web_libraries_in_flutter
    - collection_methods_unrelated_type
    - control_flow_in_finally
    - empty_statements
    - no_adjacent_strings_in_list
    - literal_only_boolean_expressions
    - no_duplicate_case_values
    - no_logic_in_create_state
    - use_key_in_widget_constructors
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_specify_types
    - annotate_overrides
    - avoid_annotating_with_dynamic
    - avoid_classes_with_only_static_members
    - avoid_double_and_int_checks
    - avoid_equals_and_hash_code_on_mutable_classes
    - avoid_field_initializers_in_const_classes
    - avoid_final_parameters
    - avoid_implementing_value_types
    - avoid_init_to_null
    - avoid_multiple_declarations_per_line
    - avoid_redundant_argument_values
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_shadowing_type_parameters
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - cast_nullable_to_non_nullable
    - curly_braces_in_flow_control_structures
    - empty_catches
    - exhaustive_cases
    - flutter_style_todos
    - join_return_with_assignment
    - missing_whitespace_between_adjacent_strings
    - prefer_contains
    - prefer_double_quotes
    - prefer_final_fields
    - prefer_final_locals
    - prefer_foreach
    - prefer_if_null_operators
    - prefer_interpolation_to_compose_strings
    - prefer_is_not_operator
    - sized_box_shrink_expand
    - sort_child_properties_last
    - sort_constructors_first
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_null_aware_assignments
    - unnecessary_null_checks
    - use_enums
    - use_if_null_to_convert_nulls_to_bools
    - use_string_buffers
    - package_names

